import crypto from 'crypto';
import type { ExecHost } from '../hosts/types';

/**
 * `maestro-sync` — the box-side sync loop (mobile-web-app spec §6.5). Sibling of
 * `maestro-drain`: uploaded content-hash-versioned, launched detached, outbound
 * HTTPS only (curl — a doctor-checked tool). It pushes journal deltas up to the
 * relay, reports each chat's queue dir, and long-polls for jobs (web sends,
 * stops, queue edits), writing them into the SAME `queue/NNNN-<turnId>.job`
 * files the drain loop already eats. No inbound port, no SSH credentials, no
 * second runtime — the box stays dumb and yours (G5).
 *
 * Single-writer clarity is preserved: drain writes the journal, sync reads it;
 * both only ever CREATE queue files (never overwrite), so the `turnId` suffix
 * keeps names unique across the two writers (§6.5 filename note).
 */

function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

const homeCache = new Map<string, Promise<string>>();
function homeFor(host: ExecHost): Promise<string> {
  let p = homeCache.get(host.id);
  if (!p) {
    p = host
      .exec('sh', ['-lc', 'printf %s "$HOME"'])
      .then((r) => r.stdout.trim() || '.')
      .catch(() => '.');
    homeCache.set(host.id, p);
  }
  return p;
}

/**
 * The shim. ~150 lines of POSIX sh + curl. Reads `~/.maestro/sync.url` +
 * `~/.maestro/sync.token`; the relay is the arbiter (409/offset), so the worst
 * failure mode is staleness, never corruption — journal pushes are read-only and
 * job writes are create-only.
 */
// NOTE: written to avoid POSIX ${...} parameter expansion so the whole script
// fits in a JS template literal (same convention as DRAIN_SH). Literal
// backslashes (tr '\n', sed '\.') are doubled; real newlines are real newlines.
export const SYNC_SH = `#!/bin/sh
# maestro-sync — see docs/specs/mobile-web-app.md §6.5. Generated by Maestro.
URL=$(cat "$HOME/.maestro/sync.url" 2>/dev/null)
TOKEN=$(cat "$HOME/.maestro/sync.token" 2>/dev/null)
[ -n "$URL" ] && [ -n "$TOKEN" ] || exit 2
BASE="$HOME/maestro/cloud"
WAIT=$MAESTRO_SYNC_WAIT; [ -n "$WAIT" ] || WAIT=5
HASH=$MAESTRO_SYNC_HASH; [ -n "$HASH" ] || HASH=unknown
UNAME=$(uname -sm 2>/dev/null | tr ' ' '_')
mkdir -p "$BASE" 2>/dev/null

# --- single instance (mkdir lock; a second launch exits if the pid is alive) ---
LOCK="$BASE/.sync.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
  pid=$(cat "$LOCK/pid" 2>/dev/null)
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then exit 0; fi
  rm -rf "$LOCK"; mkdir "$LOCK" 2>/dev/null || exit 0
fi
echo $$ > "$LOCK/pid"
cleanup() { rm -rf "$LOCK"; }
trap cleanup EXIT INT TERM

api() { # method path [extra curl args...]  (reads/writes stdin/stdout)
  m="$1"; p="$2"; shift 2
  curl -s -m 40 -X "$m" -H "Authorization: Bearer $TOKEN" "$@" "$URL$p"
}
decode() { printf '%s' "$1" | base64 --decode 2>/dev/null || printf '%s' "$1" | base64 -D 2>/dev/null; }
enc() { base64 2>/dev/null | tr -d '\\n'; }
valid() { case "$1" in *[!A-Za-z0-9_:-]*) return 1;; '') return 1;; *) return 0;; esac }

# --- push journal deltas, one chat dir at a time ---
push_journals() {
  for wsdir in "$BASE"/*/; do
    [ -d "$wsdir" ] || continue
    ws=$(basename "$wsdir"); case "$ws" in .*) continue;; esac
    for adir in "$wsdir"*/; do
      [ -d "$adir" ] || continue
      agent=$(basename "$adir")
      conv="$ws:$agent"; valid "$conv" || continue
      journal="$adir""journal.jsonl"; [ -f "$journal" ] || continue
      offf="$adir""sync.offset"
      offset=$(cat "$offf" 2>/dev/null); [ -n "$offset" ] || offset=0
      size=$(wc -c < "$journal" 2>/dev/null | tr -d ' '); [ -n "$size" ] || size=0
      if [ "$size" -lt "$offset" ]; then
        api POST /api/box/rotated -H "Content-Type: application/json" \\
          --data "{\\"conversationId\\":\\"$conv\\"}" >/dev/null 2>&1
        echo 0 > "$offf"; offset=0
      fi
      while [ "$size" -gt "$offset" ]; do
        avail=$((size - offset)); send=$avail
        [ "$send" -gt 524288 ] && send=524288
        resp=$(tail -c +$((offset + 1)) "$journal" | head -c "$send" | api POST /api/box/journal \\
          -H "maestro-conversation: $conv" -H "maestro-from-offset: $offset" \\
          -H "Content-Type: application/octet-stream" --data-binary @-)
        exp=$(printf '%s' "$resp" | grep -o '"expectedOffset":[0-9]*' | grep -o '[0-9]*')
        if [ -n "$exp" ]; then echo "$exp" > "$offf"; offset="$exp"; continue; fi
        nxt=$(printf '%s' "$resp" | grep -o '"nextOffset":[0-9]*' | grep -o '[0-9]*')
        [ -n "$nxt" ] || return 1   # network error — retry next cycle
        echo "$nxt" > "$offf"; offset="$nxt"
        size=$(wc -c < "$journal" 2>/dev/null | tr -d ' '); [ -n "$size" ] || size=0
      done
    done
  done
  return 0
}

# --- report queue dirs on change (surfaces desktop-written jobs on the phone) ---
report_queues() {
  for wsdir in "$BASE"/*/; do
    [ -d "$wsdir" ] || continue
    ws=$(basename "$wsdir"); case "$ws" in .*) continue;; esac
    for adir in "$wsdir"*/; do
      [ -d "$adir" ] || continue
      agent=$(basename "$adir"); conv="$ws:$agent"; valid "$conv" || continue
      q="$adir""queue"; [ -d "$q" ] || continue
      snap=$(ls "$q" 2>/dev/null | sort | tr '\\n' ',')
      old=$(cat "$adir"".queuesnap" 2>/dev/null)
      [ "$snap" = "$old" ] && continue
      files=""
      for f in $(ls "$q" 2>/dev/null | sort); do
        case "$f" in *.job) ;; *) continue;; esac
        tid=$(printf '%s' "$f" | sed 's/^[0-9]*-//; s/\\.job$//')
        prev=$(head -c 4096 "$q/$f" | enc)
        item="{\\"name\\":\\"$f\\",\\"turnId\\":\\"$tid\\",\\"previewB64\\":\\"$prev\\"}"
        [ -n "$files" ] && files="$files,"; files="$files$item"
      done
      api POST /api/box/queue -H "Content-Type: application/json" \\
        --data "{\\"conversationId\\":\\"$conv\\",\\"files\\":[$files]}" >/dev/null 2>&1 &&
        echo "$snap" > "$adir"".queuesnap"
    done
  done
}

# --- report git status + diff per workspace so the phone's Changes/Diff work
#     while the desktop is closed (web-desktop-parity §9.6). Throttled to 30s;
#     needs a "worktree" (+ optional "base") file the desktop drops at the ws dir. ---
report_git() {
  for wsdir in "$BASE"/*/; do
    [ -d "$wsdir" ] || continue
    ws=$(basename "$wsdir"); case "$ws" in .*) continue;; esac
    valid "$ws" || continue
    wtf="$wsdir""worktree"; [ -f "$wtf" ] || continue
    wt=$(cat "$wtf" 2>/dev/null); [ -n "$wt" ] || continue
    { [ -d "$wt/.git" ] || [ -f "$wt/.git" ]; } || continue
    base=$(cat "$wsdir""base" 2>/dev/null); [ -n "$base" ] || base=HEAD
    now=$(date +%s 2>/dev/null || echo 0)
    last=$(cat "$wsdir"".gitreport" 2>/dev/null); [ -n "$last" ] || last=0
    [ $((now - last)) -lt 30 ] && continue
    st=$(git -C "$wt" status --porcelain=v2 --branch 2>/dev/null | enc)
    pt=$(git -C "$wt" diff "$base"...HEAD 2>/dev/null | head -c 2097152 | enc)
    api POST "/api/box/workspaces/$ws/git" -H "Content-Type: application/json" \\
      --data "{\\"base\\":\\"$base\\",\\"statusB64\\":\\"$st\\",\\"patchB64\\":\\"$pt\\"}" >/dev/null 2>&1 &&
      echo "$now" > "$wsdir"".gitreport"
  done
}

ensure_drain() { # $1 = chat dir
  d="$1"
  pid=$(cat "$d/run.pid" 2>/dev/null)
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then return 0; fi
  shim="$HOME/.maestro/bin/maestro-drain"; [ -f "$shim" ] || return 0
  if command -v setsid >/dev/null 2>&1; then
    setsid sh "$shim" "$d" </dev/null >/dev/null 2>&1 &
  else
    nohup sh "$shim" "$d" </dev/null >/dev/null 2>&1 &
  fi
}

next_seq() { # $1 = queue dir -> zero-padded next NNNN
  last=$(ls "$1" 2>/dev/null | sort | tail -n 1)
  n=$(printf '%s' "$last" | sed 's/-.*//'); [ -n "$n" ] || n=0
  n=$((10#$n + 1))
  printf '%04d' "$n"
}

# --- long-poll for jobs; execute into the queue dir; ack each ---
poll_jobs() {
  qd=$(find "$BASE" -name '*.job' 2>/dev/null | wc -l | tr -d ' ')
  resp=$(api GET "/api/box/poll?wait=$WAIT&fmt=lines&shim=$HASH&uname=$UNAME&qd=$qd")
  [ -n "$resp" ] || return 0
  printf '%s\\n' "$resp" | while IFS="	" read -r jid kind conv turnid textb64; do
    [ -n "$jid" ] || continue
    valid "$conv" || continue
    ws=$(printf '%s' "$conv" | cut -d: -f1)
    agent=$(printf '%s' "$conv" | cut -d: -f2)
    dir="$BASE/$ws/$agent"; q="$dir/queue"; mkdir -p "$q" 2>/dev/null
    case "$kind" in
      message)
        nnnn=$(next_seq "$q")
        decode "$textb64" > "$q/$nnnn-$turnid.job"
        ensure_drain "$dir"
        ;;
      stop)
        pid=$(cat "$dir/run.pid" 2>/dev/null)
        if [ -n "$pid" ]; then kill -TERM -"$pid" 2>/dev/null; kill -TERM "$pid" 2>/dev/null; fi
        ;;
      queue_remove)
        rm -f "$q/"*-"$turnid".job 2>/dev/null
        ;;
      queue_edit)
        for f in "$q/"*-"$turnid".job; do [ -f "$f" ] && decode "$textb64" > "$f"; done
        ;;
    esac
    api POST "/api/box/jobs/$jid/ack" >/dev/null 2>&1
  done
  return 0
}

# --- ensure a worker is draining any chat that has staged jobs. poll_jobs only
#     kicks ensure_drain when a NEW job lands, so a job staged before maestro-drain
#     existed (or one left behind when a worker died) would otherwise sit forever.
#     This sweep makes the box run what it accepts: a synced box is never a black
#     hole. ensure_drain is idempotent (it no-ops when a live worker holds the
#     chat), so re-checking every cycle is cheap and safe. ---
drain_pending() {
  for wsdir in "$BASE"/*/; do
    [ -d "$wsdir" ] || continue
    ws=$(basename "$wsdir"); case "$ws" in .*) continue;; esac
    for adir in "$wsdir"*/; do
      [ -d "$adir" ] || continue
      q="$adir""queue"; [ -d "$q" ] || continue
      first=$(ls "$q" 2>/dev/null | grep '\\.job$' | head -n 1)
      [ -n "$first" ] || continue
      ensure_drain "$adir"
    done
  done
}

# --- main loop with jittered backoff on network failure ---
fails=0
while :; do
  ok=1
  push_journals || ok=0
  report_queues
  report_git
  poll_jobs || ok=0
  drain_pending
  if [ "$ok" -eq 0 ]; then
    fails=$((fails + 1)); [ "$fails" -gt 12 ] && fails=12
    nap=$((fails * 5)); [ "$nap" -gt 60 ] && nap=60
    jit=$(( ($$ + $(date +%s 2>/dev/null || echo 0)) % 5 ))
    sleep $((nap + jit))
  else
    fails=0
  fi
done
`;

export const SYNC_HASH = crypto.createHash('sha256').update(SYNC_SH).digest('hex').slice(0, 12);
const shimUploaded = new Set<string>(); // `${hostId}:${hash}`

/** Upload maestro-sync once per (host, content-hash). Returns its box path. */
export async function ensureSyncShim(host: ExecHost): Promise<string> {
  const home = await homeFor(host);
  const bin = host.path.join(home, '.maestro', 'bin');
  const shim = host.path.join(bin, 'maestro-sync');
  const key = `${host.id}:${SYNC_HASH}`;
  if (!shimUploaded.has(key)) {
    await host.fs.mkdirp(bin);
    await host.fs.write(shim, SYNC_SH);
    await host.fs.chmod(shim, 0o755);
    shimUploaded.add(key);
  }
  return shim;
}

/** Is the sync loop alive (lock pid points at a live process)? */
export async function syncAlive(host: ExecHost): Promise<boolean> {
  const home = await homeFor(host);
  const lockPid = host.path.join(home, 'maestro', 'cloud', '.sync.lock', 'pid');
  const r = await host.exec('sh', [
    '-lc',
    `pid=$(cat ${shq(lockPid)} 2>/dev/null); [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null && echo 1 || echo 0`,
  ]);
  return r.ok && r.stdout.trim() === '1';
}

/**
 * Provision + launch sync for a host: write sync.url/sync.token (0600), upload
 * the shim, launch it detached. Mechanism identical to `ensureDrain`
 * (setsid-else-nohup). Idempotent — a second call no-ops if the loop is alive.
 */
export async function ensureSync(host: ExecHost, relayUrl: string, boxToken: string): Promise<void> {
  const home = await homeFor(host);
  const mdir = host.path.join(home, '.maestro');
  await host.fs.mkdirp(mdir);
  await host.fs.write(host.path.join(mdir, 'sync.url'), relayUrl.replace(/\/$/, ''));
  await host.fs.write(host.path.join(mdir, 'sync.token'), boxToken);
  await host.fs.chmod(host.path.join(mdir, 'sync.url'), 0o600).catch(() => {});
  await host.fs.chmod(host.path.join(mdir, 'sync.token'), 0o600).catch(() => {});
  const shim = await ensureSyncShim(host);
  if (await syncAlive(host)) return;
  const launcher = `if command -v setsid >/dev/null 2>&1; then setsid sh ${shq(shim)}; else nohup sh ${shq(shim)}; fi`;
  await host.exec('sh', [
    '-lc',
    `export MAESTRO_SYNC_HASH=${shq(SYNC_HASH)}; export PATH="$HOME/.maestro/bin:$PATH"; ${launcher} </dev/null >/dev/null 2>&1 &`,
  ]);
}

/** Stop + remove sync (unlink): kill the loop, delete the token/url + shim. */
export async function teardownSync(host: ExecHost): Promise<void> {
  const home = await homeFor(host);
  const lockPid = host.path.join(home, 'maestro', 'cloud', '.sync.lock', 'pid');
  const mdir = host.path.join(home, '.maestro');
  await host
    .exec('sh', [
      '-lc',
      `pid=$(cat ${shq(lockPid)} 2>/dev/null); [ -n "$pid" ] && kill -TERM "$pid" 2>/dev/null; ` +
        `rm -f ${shq(host.path.join(mdir, 'sync.token'))} ${shq(host.path.join(mdir, 'sync.url'))} ${shq(host.path.join(mdir, 'bin', 'maestro-sync'))} 2>/dev/null; true`,
    ])
    .catch(() => {});
  shimUploaded.clear();
}

/** The exact crontab lines the "keep running after reboots" option installs,
 *  shown to the user verbatim before writing (§6.5). */
export function syncCrontabLines(): string[] {
  const launch = `sh "$HOME/.maestro/bin/maestro-sync"`;
  return [
    `@reboot MAESTRO_SYNC_HASH=${SYNC_HASH} ${launch} >/dev/null 2>&1`,
    `*/10 * * * * [ -f "$HOME/maestro/cloud/.sync.lock/pid" ] && kill -0 "$(cat "$HOME/maestro/cloud/.sync.lock/pid")" 2>/dev/null || MAESTRO_SYNC_HASH=${SYNC_HASH} ${launch} >/dev/null 2>&1`,
  ];
}

const CRON_MARK = '# maestro-sync (managed)';

/** Install the reboot/watchdog crontab lines (idempotent — removes prior copy). */
export async function installSyncCron(host: ExecHost): Promise<void> {
  const lines = [CRON_MARK, ...syncCrontabLines(), `${CRON_MARK}-end`].join('\n');
  await host.exec('sh', [
    '-lc',
    `cur=$(crontab -l 2>/dev/null | sed '/${CRON_MARK.replace(/[/]/g, '\\/')}/,/${CRON_MARK.replace(/[/]/g, '\\/')}-end/d'); ` +
      `printf '%s\\n%s\\n' "$cur" ${shq(lines)} | crontab - 2>/dev/null; true`,
  ]).catch(() => {});
}

export async function removeSyncCron(host: ExecHost): Promise<void> {
  await host.exec('sh', [
    '-lc',
    `crontab -l 2>/dev/null | sed '/${CRON_MARK.replace(/[/]/g, '\\/')}/,/${CRON_MARK.replace(/[/]/g, '\\/')}-end/d' | crontab - 2>/dev/null; true`,
  ]).catch(() => {});
}

/** Doctor row state for maestro-sync: running / installed / not installed (§6.5). */
export async function syncStatus(host: ExecHost): Promise<'running' | 'installed' | 'missing'> {
  if (await syncAlive(host)) return 'running';
  const home = await homeFor(host);
  const shim = host.path.join(home, '.maestro', 'bin', 'maestro-sync');
  const r = await host.exec('sh', ['-lc', `[ -f ${shq(shim)} ] && echo 1 || echo 0`]);
  return r.ok && r.stdout.trim() === '1' ? 'installed' : 'missing';
}
