import crypto from 'crypto';
import { Notification } from 'electron';
import { broadcast, getWindow } from '../bus';
import { appIconPath } from '../icon';
import { Messages, Projects, Scheduled, Settings, Workspaces, now } from '../db';
import { hostForWorkspace, isCloudWorkspace } from '../hosts';
import type { ExecHost } from '../hosts/types';
import { JournalChild, parseFrame, readJournalFrom } from '../hosts/journal';
import { adapters, beginTurn, isAgentRunning, resolveTurn, setAwayDigestHook } from './harness';
import { boxLinkedForHost } from './account';
import { fireRemoteScheduled, pokeScheduler } from './schedule';
import type { BuildOpts } from './harness/adapter';
import type { Workspace } from '../../shared/types';

/**
 * Cloud continuation (spec §6.2–6.5). A per-chat directory on the box holds a
 * journal, a queue of job files, and the `turn.sh` invocation. A tiny uploaded
 * POSIX `maestro-drain` runs the harness CLI detached, appends its NDJSON to the
 * journal, and drains the queue — so a turn (and, for recipe harnesses, the
 * whole queue) runs to completion even with the app closed. The app is a viewer
 * that tails the journal and replays it through the same adapter pipeline a live
 * turn uses (`beginTurn` → `finalize`), so there is no server twin of anything.
 */

// POSIX single-quote a shell argument.
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

// ---------- on-box layout ----------

const homeCache = new Map<string, Promise<string>>();

/** The box's $HOME (cached per host). */
function homeFor(host: ExecHost): Promise<string> {
  let p = homeCache.get(host.id);
  if (!p) {
    p = host
      .exec('sh', ['-lc', 'printf %s "$HOME"'])
      .then((r) => r.stdout.trim() || '.')
      .catch(() => '.');
    homeCache.set(host.id, p);
  }
  return p;
}

interface ChatPaths {
  dir: string;
  journal: string;
  queue: string;
  scheduled: string;
  runPid: string;
  turnSh: string;
  stderr: string;
}

async function chatPaths(host: ExecHost, ws: Workspace, agentId: number): Promise<ChatPaths> {
  const home = await homeFor(host);
  const dir = host.path.join(home, 'maestro', 'cloud', ws.id, String(agentId));
  return {
    dir,
    journal: host.path.join(dir, 'journal.jsonl'),
    queue: host.path.join(dir, 'queue'),
    scheduled: host.path.join(dir, 'scheduled'),
    runPid: host.path.join(dir, 'run.pid'),
    turnSh: host.path.join(dir, 'turn.sh'),
    stderr: host.path.join(dir, 'stderr.log'),
  };
}

// ---------- the drain shim ----------

/**
 * `maestro-drain <chat-dir>` — the single-writer loop (cloud-continuation §6.2 +
 * september-batch §4). Runs each queued job through `turn.sh`, framing the
 * journal before and after each turn so the app's parser sees clean turn
 * boundaries around verbatim CLI output. A directory lock keeps exactly one
 * drain per chat (a stale lock whose owner is dead is taken over). A TERM trap
 * aborts the in-flight turn (chat:stop). New in §4: due jobs in `scheduled/` are
 * promoted into `queue/` and run like any other job, and a drain with only
 * future scheduled jobs *naps* (≤60s slices, USR1 cuts a nap short) instead of
 * exiting. Launched detached (setsid) so it outlives the app.
 */
const DRAIN_SH = `#!/bin/sh
# maestro-drain — docs/specs/cloud-continuation.md §6.2 + september-batch.md §4. Generated by Maestro.
dir="$1"
[ -n "$dir" ] || exit 2
cd "$dir" 2>/dev/null || exit 2
# One drain per chat: the lock is a directory (mkdir is atomic). A lock whose
# owner (run.pid) is dead is stale — a reboot mid-turn or mid-nap — and is taken
# over; otherwise a single reboot would block every future turn of this chat.
if ! mkdir .lock 2>/dev/null; then
  pid=$(cat run.pid 2>/dev/null)
  [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null && exit 0
  rm -rf .lock
  mkdir .lock 2>/dev/null || exit 0
fi
child=""      # the in-flight turn (turn.sh)
napper=""     # the sleep until the next scheduled job is due
turnid=""
cleanup() { rm -rf .lock; rm -f run.pid; }
onterm() {
  [ -n "$napper" ] && kill "$napper" 2>/dev/null
  if [ -n "$child" ]; then
    kill -TERM "$child" 2>/dev/null
    ts=$(date +%s 2>/dev/null || echo 0)
    [ -n "$turnid" ] && printf '{"maestro":"turn-end","turnId":"%s","exit":143,"at":%s}\\n' "$turnid" "$ts" >> "$JOURNAL"
  fi
  cleanup; exit 143
}
# USR1 = "something new in queue/": cut the nap short. Only trapped while
# napping — an ignored signal can't interrupt the wait on a running turn.
onwake() { [ -n "$napper" ] && kill "$napper" 2>/dev/null; }
trap onterm TERM INT
trap '' USR1
trap cleanup EXIT
echo $$ > run.pid
JOURNAL="$dir/journal.jsonl"
: >> "$JOURNAL"
# Move every due scheduled job into queue/, numbered after the last queued one.
# Leading zeros are stripped before arithmetic (0010 would be octal).
promote() {
  now=$(date +%s)
  for f in $(ls scheduled 2>/dev/null | sort); do
    due=$(printf '%s' "$f" | sed 's/-.*//; s/^0*//')
    [ "\${due:-0}" -le "$now" ] || break
    last=$(ls queue 2>/dev/null | sort | tail -n 1 | sed 's/-.*//; s/^0*//')
    mkdir -p queue
    mv "scheduled/$f" "queue/$(printf '%04d' $(( \${last:-0} + 1 )))-$(printf '%s' "$f" | sed 's/^[0-9]*-//')"
  done
}
while :; do
  promote
  next=$(ls queue 2>/dev/null | sort | head -n 1)
  if [ -z "$next" ]; then
    soon=$(ls scheduled 2>/dev/null | sort | head -n 1)
    [ -n "$soon" ] || break                     # nothing queued, nothing scheduled: done
    due=$(printf '%s' "$soon" | sed 's/-.*//; s/^0*//')
    nap=$(( \${due:-0} - $(date +%s) ))
    [ "$nap" -gt 60 ] && nap=60                 # short naps: survive clock jumps, re-check often
    [ "$nap" -lt 1 ] && nap=1
    trap onwake USR1
    sleep "$nap" & napper=$!
    wait "$napper" 2>/dev/null
    napper=""
    trap '' USR1
    continue
  fi
  job="queue/$next"
  turnid=$(printf '%s' "$next" | sed 's/^[0-9]*-//; s/\\.job$//')
  ts=$(date +%s 2>/dev/null || echo 0)
  printf '{"maestro":"turn-start","turnId":"%s","at":%s}\\n' "$turnid" "$ts" >> "$JOURNAL"
  MAESTRO_JOURNAL="$JOURNAL" sh turn.sh < "$job" >> "$JOURNAL" 2>> stderr.log &
  child=$!
  wait "$child"
  code=$?
  child=""
  wait 2>/dev/null                              # reap any lingering grandchildren (§10)
  ts=$(date +%s 2>/dev/null || echo 0)
  printf '{"maestro":"turn-end","turnId":"%s","exit":%d,"at":%s}\\n' "$turnid" "$code" "$ts" >> "$JOURNAL"
  rm -f "$job"
  turnid=""
done
`;

/** The drain script source, for the drain-e2e harness (§4.8) to run under a real
 *  `sh` without SSH. */
export function getDrainScript(): string {
  return DRAIN_SH;
}

const DRAIN_HASH = crypto.createHash('sha256').update(DRAIN_SH).digest('hex').slice(0, 12);
const shimUploaded = new Set<string>(); // `${hostId}:${hash}`

/** Upload maestro-drain once per (host, content-hash) — same mechanism as the
 *  bridge shims (§6.2). Returns its absolute path on the box. Exported so box
 *  provisioning (account.ts) can install the worker alongside maestro-sync: a
 *  synced box must always be able to *run* the web jobs it accepts, not just
 *  stage them (maestro-sync's ensure_drain silently no-ops when the shim is
 *  absent — the "accepts work it can't run" black hole). */
export async function ensureDrainShim(host: ExecHost): Promise<string> {
  const home = await homeFor(host);
  const bin = host.path.join(home, '.maestro', 'bin');
  const shim = host.path.join(bin, 'maestro-drain');
  const key = `${host.id}:${DRAIN_HASH}`;
  if (!shimUploaded.has(key)) {
    await host.fs.mkdirp(bin);
    await host.fs.write(shim, DRAIN_SH);
    await host.fs.chmod(shim, 0o755);
    shimUploaded.add(key);
  }
  return shim;
}

// ---------- turn.sh + job files ----------

const SES = '__MAESTRO_SESSION__';
const PRM = '__MAESTRO_PROMPT__';

/** Shell-quote adapter args, mapping the session/prompt sentinels to the shell
 *  expansions turn.sh fills in at run time. */
function quoteArgs(args: string[]): string {
  return args.map((a) => (a === SES ? '"$SESSION"' : a === PRM ? '"$PROMPT"' : shq(a))).join(' ');
}

/**
 * Generate the per-chat `turn.sh`: the exact harness invocation with the session
 * id spliced in from the journal (recipe harnesses) and the prompt fed from the
 * job file. Built by calling the adapter twice — first turn (no resume) and
 * resume (sentinel session id) — so the adapter stays the single source of the
 * command shape.
 */
function buildTurnScript(
  ws: Workspace,
  base: Omit<BuildOpts, 'prompt' | 'sessionId'>,
  env: Record<string, string>
): string {
  const adapter = adapters[ws.harness];
  const probe = adapter.build({ ...base, prompt: PRM, sessionId: null });
  const promptInArgs = probe.stdin === null; // raw adapters carry the prompt as an arg
  // Arg-prompt adapters get a null system prompt in turn.sh (the job file already
  // carries prompt+system via promptWithSystem); stdin adapters keep it in args.
  const scriptBase = promptInArgs ? { ...base, systemPrompt: null } : base;
  const first = adapter.build({ ...scriptBase, prompt: PRM, sessionId: null });
  const resume = adapter.build({ ...scriptBase, prompt: PRM, sessionId: SES });
  const recipe = adapter.unattendedDrain?.sessionRecipe;

  const lines = ['#!/bin/sh', '# Generated by Maestro (cloud continuation §6.2).'];
  lines.push('export PATH="$HOME/.maestro/bin:$PATH"');
  // The CLI runs IN the worktree (the drain loop itself sits in the chat dir);
  // the journal path is absolute, so writes still land correctly.
  lines.push(`cd ${shq(ws.worktreePath)} || exit 1`);
  for (const [k, v] of Object.entries(env)) lines.push(`export ${k}=${shq(v)}`);
  if (promptInArgs) lines.push('PROMPT=$(cat)');
  lines.push(recipe ? `SESSION=$(${recipe})` : 'SESSION=');
  lines.push('if [ -n "$SESSION" ]; then');
  lines.push(`  exec ${shq(resume.cmd)} ${quoteArgs(resume.args)}`);
  lines.push('else');
  lines.push(`  exec ${shq(first.cmd)} ${quoteArgs(first.args)}`);
  lines.push('fi');
  return lines.join('\n') + '\n';
}

/** The per-message input the box feeds the CLI: the adapter's own stdin for
 *  stdin harnesses (claude prompt / codex system+prompt), or the prompt arg for
 *  arg harnesses (opencode). */
function jobContent(ws: Workspace, base: Omit<BuildOpts, 'prompt' | 'sessionId'>, prompt: string): string {
  const cmd = adapters[ws.harness].build({ ...base, prompt, sessionId: null });
  return cmd.stdin ?? cmd.args[cmd.args.length - 1] ?? prompt;
}

const seqOf = (n: number) => String(n).padStart(4, '0');

// ---------- drain lifecycle ----------

/** Is a drain loop currently alive for this chat (run.pid points at a live pid)? */
async function drainAlive(host: ExecHost, p: ChatPaths): Promise<boolean> {
  const r = await host.exec('sh', [
    '-lc',
    `pid=$(cat ${shq(p.runPid)} 2>/dev/null); [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null && echo 1 || echo 0`,
  ]);
  return r.ok && r.stdout.trim() === '1';
}

/** Launch the drain loop detached, if one isn't already running. If it IS alive,
 *  nudge it (USR1) so a nap ends and a freshly written job runs now rather than
 *  up to 60s later (§4.3). */
async function ensureDrain(host: ExecHost, ws: Workspace, agentId: number): Promise<void> {
  const p = await chatPaths(host, ws, agentId);
  if (await drainAlive(host, p)) {
    await host
      .exec('sh', ['-lc', `pid=$(cat ${shq(p.runPid)} 2>/dev/null); [ -n "$pid" ] && kill -USR1 "$pid" 2>/dev/null; true`])
      .catch(() => {});
    return;
  }
  const shim = await ensureDrainShim(host);
  // setsid where available (clean process-group kill), else nohup; either way the
  // child inherits the login PATH the exec channel resolved. Detach all stdio so
  // it survives channel close, app quit, and sshd restart.
  const launcher = `if command -v setsid >/dev/null 2>&1; then setsid sh ${shq(shim)} ${shq(p.dir)}; else nohup sh ${shq(shim)} ${shq(p.dir)}; fi`;
  await host.exec('sh', ['-lc', `export PATH="$HOME/.maestro/bin:$PATH"; ${launcher} </dev/null >/dev/null 2>&1 &`]);
}

/**
 * Queue a cloud turn: write `turn.sh` (fresh, in case the system prompt/model
 * changed) and the job file, then make sure the drain loop and the app-side
 * follower are running. The box drains it in `seq` order — attended or not.
 */
export async function writeTurnJob(opts: {
  ws: Workspace;
  agentId: number;
  turnId: string;
  prompt: string;
  systemPrompt: string | null;
  env: Record<string, string>;
}): Promise<{ ok: boolean; error?: string }> {
  const { ws, agentId, turnId } = opts;
  const host = hostForWorkspace(ws);
  try {
    const { base, spawnEnv } = resolveTurn(ws, agentId, opts.systemPrompt, opts.env);
    const p = await chatPaths(host, ws, agentId);
    await host.fs.mkdirp(p.queue);
    await host.exec('chmod', ['700', p.dir]).catch(() => {}); // 0700 (§6.9)
    // Drop the worktree path + base ref at the workspace dir so maestro-sync's
    // report_git can produce Changes/Diff for the phone while the desktop is
    // closed (web-desktop-parity §9.6).
    const wsDir = host.path.dirname(p.dir);
    await host.fs.write(host.path.join(wsDir, 'worktree'), ws.worktreePath).catch(() => {});
    await host.fs.write(host.path.join(wsDir, 'base'), Projects.get(ws.projectId)?.baseBranch ?? 'HEAD').catch(() => {});
    await host.fs.write(p.turnSh, buildTurnScript(ws, base, spawnEnv));
    // seq = one past the highest existing job so ordering is stable across a
    // burst of sends; the box drains lexically.
    const listing = await host.exec('sh', ['-lc', `ls ${shq(p.queue)} 2>/dev/null | sort | tail -n 1`]);
    const lastSeq = parseInt(listing.stdout.trim().split('-')[0] || '0', 10) || 0;
    const jobPath = host.path.join(p.queue, `${seqOf(lastSeq + 1)}-${turnId}.job`);
    await host.fs.write(jobPath, jobContent(ws, base, opts.prompt));
    await ensureDrain(host, ws, agentId);
    startFollower(ws, agentId);
    return { ok: true };
  } catch (e: any) {
    return { ok: false, error: String(e?.message ?? e) };
  }
}

/** The scheduled-job filename: epoch SECONDS zero-padded to 10 digits (so
 *  `ls | sort` is chronological), then the turnId (§4.2). */
export function scheduledJobName(deliverAt: number, turnId: string): string {
  return `${String(Math.floor(deliverAt / 1000)).padStart(10, '0')}-${turnId}.job`;
}

/**
 * Write a box-owned scheduled message: a job file with a due time in `scheduled/`
 * (§4). Identical to writeTurnJob except it lands in scheduled/, and it wakes the
 * drain (which naps until due) but does NOT start the follower — the scheduler
 * does that at fire time (wakeScheduled). Still rewrites turn.sh so a chat whose
 * very first message is scheduled has one.
 */
export async function writeScheduledJob(opts: {
  ws: Workspace;
  agentId: number;
  turnId: string;
  deliverAt: number;
  prompt: string;
  systemPrompt: string | null;
  env: Record<string, string>;
}): Promise<{ ok: boolean; error?: string }> {
  const { ws, agentId, turnId, deliverAt } = opts;
  const host = hostForWorkspace(ws);
  try {
    const { base, spawnEnv } = resolveTurn(ws, agentId, opts.systemPrompt, opts.env);
    const p = await chatPaths(host, ws, agentId);
    await host.fs.mkdirp(p.scheduled);
    await host.exec('chmod', ['700', p.dir]).catch(() => {}); // 0700 (§6.9)
    await host.fs.write(p.turnSh, buildTurnScript(ws, base, spawnEnv));
    await host.fs.write(host.path.join(p.scheduled, scheduledJobName(deliverAt, turnId)), jobContent(ws, base, opts.prompt));
    await ensureDrain(host, ws, agentId); // start (or wake) the napping drain
    return { ok: true };
  } catch (e: any) {
    return { ok: false, error: String(e?.message ?? e) };
  }
}

/** Remove a scheduled job file (cancel / edit / send-now). `ok:false` only when
 *  the host is unreachable — the caller keeps the row and reports (§4.3). */
export async function removeScheduledJob(
  ws: Workspace,
  agentId: number,
  turnId: string
): Promise<{ ok: boolean; error?: string }> {
  const host = hostForWorkspace(ws);
  try {
    const p = await chatPaths(host, ws, agentId);
    await host.exec('sh', [
      '-lc',
      `rm -f ${shq(p.scheduled)}/*-${turnId}.job ${shq(p.queue)}/*-${turnId}.job 2>/dev/null; true`,
    ]);
    return { ok: true };
  } catch (e: any) {
    return { ok: false, error: String(e?.message ?? e) };
  }
}

/** deliverAt reached for a box-owned row: make sure the drain (which owns
 *  delivery) and the follower (which turns the fired turn into a message) are up.
 *  Idempotent — ensureDrain nudges a live drain, startFollower is a no-op if one
 *  runs (§4.3/§4.5). */
export async function wakeScheduled(ws: Workspace, agentId: number): Promise<void> {
  const host = hostForWorkspace(ws);
  await ensureDrain(host, ws, agentId);
  startFollower(ws, agentId);
}

/** Stop a cloud chat (chat:stop): clear pending jobs and kill the drain group.
 *  Leaves scheduled/ alone (stop is about the queue). If future scheduled jobs
 *  remain, the napping drain died with the group, so relaunch it once run.pid is
 *  gone (§4.3). */
export async function stopCloudTurn(ws: Workspace, agentId: number): Promise<void> {
  const host = hostForWorkspace(ws);
  const p = await chatPaths(host, ws, agentId).catch(() => null);
  if (!p) return;
  await host
    .exec('sh', [
      '-lc',
      `rm -f ${shq(p.queue)}/*.job 2>/dev/null; ` +
        `pid=$(cat ${shq(p.runPid)} 2>/dev/null); ` +
        `[ -n "$pid" ] && { kill -TERM -"$pid" 2>/dev/null; kill -TERM "$pid" 2>/dev/null; }; ` +
        // If anything is still scheduled, wait for the drain to actually exit, then
        // relaunch so the nap resumes. (Empty scheduled/ ⇒ nothing to relaunch.)
        `if ls ${shq(p.scheduled)}/*.job >/dev/null 2>&1; then ` +
        `i=0; while [ -f ${shq(p.runPid)} ] && [ $i -lt 3 ]; do sleep 1; i=$((i+1)); done; fi; true`,
    ])
    .catch(() => {});
  // Relaunch outside the kill exec so it uses the normal detached launcher.
  const stillScheduled = await host
    .exec('sh', ['-lc', `ls ${shq(p.scheduled)}/*.job >/dev/null 2>&1 && echo 1 || echo 0`])
    .then((r) => r.stdout.trim() === '1')
    .catch(() => false);
  if (stillScheduled) await ensureDrain(host, ws, agentId).catch(() => {});
}

/** Remove pending jobs without killing a running turn (clearQueue). */
export async function clearCloudJobs(ws: Workspace, agentId: number): Promise<void> {
  const host = hostForWorkspace(ws);
  const p = await chatPaths(host, ws, agentId).catch(() => null);
  if (!p) return;
  await host.exec('sh', ['-lc', `rm -f ${shq(p.queue)}/*.job 2>/dev/null; true`]).catch(() => {});
}

/** Best-effort kill of a chat's drain group (used by the JournalChild's kill()). */
async function killChat(host: ExecHost, p: ChatPaths): Promise<void> {
  await host
    .exec('sh', [
      '-lc',
      `pid=$(cat ${shq(p.runPid)} 2>/dev/null); [ -n "$pid" ] && { kill -TERM -"$pid" 2>/dev/null; kill -TERM "$pid" 2>/dev/null; }; true`,
    ])
    .catch(() => {});
}

// ---------- the journal follower ----------

interface Follower {
  stop: () => void;
}
const followers = new Map<string, Follower>(); // `${wsId}:${agentId}`
const fKey = (wsId: string, agentId: number) => `${wsId}:${agentId}`;

const POLL_MS = 1000;

/** Start (or keep) the follower for a cloud chat: it tails the journal from the
 *  stored offset, replays completed turns through `finalize`, and stays attached
 *  to a live turn. Idempotent. */
export function startFollower(ws: Workspace, agentId: number): void {
  const key = fKey(ws.id, agentId);
  if (followers.has(key)) return;
  const host = hostForWorkspace(ws);
  let stopped = false;
  let timer: NodeJS.Timeout | null = null;

  // Per-turn state carried across polls (a live turn spans several reads).
  // readOffset advances per line (in-memory); the persisted journalOffset only
  // moves at turn boundaries, so catch-up resumes at a clean turn edge and we
  // don't broadcast chat:meta on every CLI line.
  let readOffset = Workspaces.getChats(ws.id)[String(agentId)]?.journalOffset ?? 0;
  let current: { child: JournalChild; turnId: string; done: Promise<void> } | null = null;
  let carry = ''; // partial trailing line

  const persistOffset = () => Workspaces.patchChat(ws.id, agentId, { journalOffset: readOffset });

  const finish = () => {
    stopped = true;
    if (timer) clearTimeout(timer);
    followers.delete(key);
  };

  const poll = async () => {
    if (stopped) return;
    let p: ChatPaths;
    try {
      p = await chatPaths(host, ws, agentId);
    } catch {
      timer = setTimeout(poll, POLL_MS);
      return;
    }
    let read: { data: string; size: number };
    try {
      read = await readJournalFrom(host, p.journal, readOffset);
    } catch {
      timer = setTimeout(poll, POLL_MS);
      return;
    }
    const buf = carry + read.data;
    const nl = buf.lastIndexOf('\n');
    const complete = nl >= 0 ? buf.slice(0, nl + 1) : '';
    carry = nl >= 0 ? buf.slice(nl + 1) : buf;
    const lines = complete.length ? complete.slice(0, -1).split('\n') : [];

    for (let i = 0; i < lines.length; i++) {
      if (stopped) return;
      const line = lines[i];
      const lineBytes = Buffer.byteLength(line + '\n', 'utf8');
      const frame = parseFrame(line);
      if (frame?.kind === 'turn-start') {
        // A box-owned scheduled row fired: record its user message and drop the
        // row. No-op unless a row carries this remoteTurnId, so replays after
        // rotation are idempotent (§4.5).
        fireRemoteScheduled(frame.turnId, frame.at ? frame.at * 1000 : Date.now());
        // Idempotency: a turn already materialized (its agent message exists) is
        // skipped — only its bytes are stepped over.
        if (Messages.exists(frame.turnId)) {
          readOffset += lineBytes;
          persistOffset();
          continue;
        }
        const adapter = adapters[ws.harness];
        if (isAgentRunning(ws.id, agentId)) {
          // Another turn is somehow live — don't double-register; step over.
          readOffset += lineBytes;
          continue;
        }
        // Quiet (no per-turn notification) when this turn is already complete in
        // the buffer — i.e. a historical replay, not a live turn (§6.5).
        const quiet = lines.slice(i + 1).some((l) => {
          const f = parseFrame(l);
          return f?.kind === 'turn-end' && f.turnId === frame.turnId;
        });
        let resolveDone!: () => void;
        const done = new Promise<void>((r) => (resolveDone = r));
        const child = new JournalChild(() => void killChat(host, p));
        current = { child, turnId: frame.turnId, done };
        beginTurn(ws, agentId, adapter, child, {
          turnId: frame.turnId,
          stdin: null,
          cmdName: adapter.id,
          quiet,
          onFinalized: () => resolveDone(),
        });
        readOffset += lineBytes;
      } else if (frame?.kind === 'turn-end') {
        readOffset += lineBytes;
        if (current && current.turnId === frame.turnId) {
          try {
            const tail = await readStderrTail(host, p);
            if (frame.exit !== 0 && tail) current.child.pushStderr(tail);
          } catch {}
          current.child.close(frame.exit);
          const c = current;
          current = null;
          await c.done; // let finalize land before we advance the durable cursor
        }
        persistOffset(); // a turn boundary — safe, idempotent resume point
      } else {
        if (current) current.child.pushLine(line);
        readOffset += lineBytes;
      }
    }

    if (stopped) return;
    // Idle: no live turn, caught up to EOF, AND no queued job pending. The drain
    // may still be *alive but napping* on a future scheduled job (§4) — so split
    // the two cases.
    if (!current && !carry && read.size <= readOffset) {
      const alive = await drainAlive(host, p);
      const pending = (await host.exec('sh', ['-lc', `ls ${shq(p.queue)}/*.job 2>/dev/null | head -1`])).stdout.trim();
      if (!alive && !pending) {
        // The chat is quiescent: rotate the journal so files stay small (§6.3) and
        // stand down; the next send (or reconnect) starts a fresh follower.
        await rotateJournal(host, p).catch(() => {});
        readOffset = Workspaces.getChats(ws.id)[String(agentId)]?.journalOffset ?? 0;
        finish();
        return;
      }
      // Napping drain, empty queue, nothing due for a while: stand down without
      // rotating (the drain still holds the journal). The scheduler's timer starts
      // a fresh follower at deliverAt (wakeScheduled).
      if (alive && !pending && Scheduled.nextRemoteAt(ws.id, agentId, now() + 2 * POLL_MS) !== null) {
        finish();
        return;
      }
    }
    timer = setTimeout(poll, POLL_MS);
  };

  followers.set(key, { stop: finish });
  void poll();
}

/** Interrupted-turn stderr, for the "interrupted on <host>" finalize (§6.3). */
async function readStderrTail(host: ExecHost, p: ChatPaths): Promise<string> {
  const r = await host.exec('sh', ['-lc', `tail -c 2000 ${shq(p.stderr)} 2>/dev/null`]);
  return r.ok ? r.stdout : '';
}

/**
 * Shrink an idle chat's journal, but PRESERVE session continuity: the unattended
 * drain recipes recover the next turn's resume id by grepping the journal, so a
 * naive truncate-to-empty would make every post-rotation turn start fresh. Keep
 * the last session/thread-id marker (claude/codex resume) and the last turn-end
 * (opencode `--continue` detection); everything else is display history the app
 * already materialized into SQLite. The offset advances past the kept lines so
 * the follower treats them as already-seen.
 */
async function rotateJournal(host: ExecHost, p: ChatPaths): Promise<void> {
  // Rotation guard (mobile-web §6.5): if a Maestro Web box is linked to this
  // host, don't rotate until the relay has ingested the whole journal — else the
  // sync loop would lose a tail it hasn't pushed. One extra SFTP read. Once the
  // relay is caught up we still rotate (preserving continuity below); its own
  // shrink handling (size < offset ⇒ POST /rotated + reset) copes with the
  // smaller file.
  if (boxLinkedForHost(host.id)) {
    const off = host.path.join(p.dir, 'sync.offset');
    const g = await host.exec('sh', [
      '-lc',
      `off=$(cat ${shq(off)} 2>/dev/null); sz=$(wc -c < ${shq(p.journal)} 2>/dev/null | tr -d ' '); echo "$off:$sz"`,
    ]);
    const [o, s] = (g.stdout.trim() || '0:0').split(':');
    if ((Number(o) || 0) < (Number(s) || 0)) return; // relay behind — keep the journal
  }
  const r = await host.exec('sh', [
    '-lc',
    `j=${shq(p.journal)}; t="$j.rot"; ` +
      `{ grep -E '"(session_id|thread_id)":' "$j" 2>/dev/null | tail -n 1; ` +
      `grep '"maestro":"turn-end"' "$j" 2>/dev/null | tail -n 1; } > "$t" 2>/dev/null; ` +
      `mv "$t" "$j" 2>/dev/null; : > ${shq(p.stderr)} 2>/dev/null; wc -c < "$j" 2>/dev/null || echo 0`,
  ]);
  const size = parseInt(r.stdout.trim(), 10) || 0;
  const parts = p.dir.split('/');
  const agentId = Number(parts[parts.length - 1]);
  const wsId = parts[parts.length - 2];
  Workspaces.patchChat(wsId, agentId, { journalOffset: size });
}

// ---------- catch-up (boot + reconnect) ----------

let digest = { finished: 0, attention: 0 };

/** Kick every follower for one cloud workspace's chats (§4.3). It replays from
 *  journalOffset, then either stands down or stays attached to a live turn. Used
 *  by boot catch-up and by restore (§8), which un-archives a workspace the
 *  followers skipped while it was archived. */
export function catchUpWorkspace(ws: Workspace): void {
  const chats = Workspaces.getChats(ws.id);
  const ids = new Set<number>([1]);
  for (const k of Object.keys(chats)) ids.add(Number(k));
  for (const id of ids) startFollower(ws, id);
}

/** Replay + attach every cloud chat's journal (spec §6.3). Historical turns
 *  finalize quietly and roll up into one away-digest notification. */
export async function catchUpAll(): Promise<void> {
  digest = { finished: 0, attention: 0 };
  setAwayDigestHook(({ attention }) => {
    digest.finished++;
    if (attention) digest.attention++;
  });
  const cloudWss = Workspaces.list().filter((ws) => !ws.archived && isCloudWorkspace(ws));
  // Give the initial replays a moment, then post the digest and hand
  // notifications back to the live path.
  for (const ws of cloudWss) catchUpWorkspace(ws);
  await new Promise((r) => setTimeout(r, cloudWss.length ? 4000 : 0));
  setAwayDigestHook(null);
  postDigest();
}

/** Reconnect catch-up: re-tail cloud chats whose host just came back. */
export function reconnectCatchUp(hostId: string): void {
  for (const { ws, agentId } of cloudChats()) {
    if (hostForWorkspace(ws).id === hostId) startFollower(ws, agentId);
  }
  // Overdue remote rows whose drains napped through the disconnect need their
  // followers/drains re-woken (§4.3).
  pokeScheduler();
}

/** Every (cloud workspace, chat) pair that could have journalled activity. */
function cloudChats(): { ws: Workspace; agentId: number }[] {
  const out: { ws: Workspace; agentId: number }[] = [];
  for (const ws of Workspaces.list()) {
    if (ws.archived || !isCloudWorkspace(ws)) continue;
    const chats = Workspaces.getChats(ws.id);
    const ids = new Set<number>([1]);
    for (const k of Object.keys(chats)) ids.add(Number(k));
    for (const id of ids) out.push({ ws, agentId: id });
  }
  return out;
}

function postDigest(): void {
  const { finished, attention } = digest;
  if (!finished) return;
  const win = getWindow();
  if (!Settings.global().notifications || !win || win.isFocused() || !Notification.isSupported()) return;
  const bits = [`${finished} conversation${finished === 1 ? '' : 's'} finished`];
  if (attention) bits.push(`${attention} need${attention === 1 ? 's' : ''} attention`);
  new Notification({ title: 'While you were away', body: bits.join(', ') + '.', icon: appIconPath() }).show();
}

/** Stop one chat's follower (delete / bring-local) so it can't re-materialize
 *  messages from a journal that no longer belongs to a cloud chat. */
export function stopFollower(workspaceId: string, agentId: number): void {
  followers.get(fKey(workspaceId, agentId))?.stop();
}

/** Stop every follower (app quit) — the box keeps running; we just stop tailing. */
export function stopAllFollowers(): void {
  for (const f of [...followers.values()]) f.stop();
  followers.clear();
}
